# Step 1: Build the Next.js application
# Use an official Node.js as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# # Copy package.json and package-lock.json to work directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Copy the built app and the .next folder from the builder stage
# COPY /app/public ./public
# COPY /app/.next ./.next
# COPY /app/node_modules ./node_modules
# COPY /app/package.json ./package.json

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]