name: Deploy athlabs-frontend production branch main on GCP VM
on: 
  push: 
    branches: 
      - main
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Get Github action IP 
        id: ip 
        uses: haythem/public-ip@v1.3
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Cloud Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Add Github Actions IP to GCP Firewall
        run: |
          gcloud compute firewall-rules create allow-ssh-from-github --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=tcp:22 --source-ranges=${{ steps.ip.outputs.ipv4 }}

      - name: Deploy on Google Cloud VM
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PK }}
          HOSTNAME: ${{ secrets.HOSTNAME_PROD }}
          USER_NAME: ${{ secrets.USERNAME_PROD }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            cd /home/aip/athlabs-main/athlabs-frontend
            git checkout main
            git pull origin main
            cd /home/aip/athlabs-main
            docker compose build frontend
            docker compose stop frontend
            yes | docker compose rm frontend
            docker compose up -d frontend
            yes | docker system prune -a --volumes
          '
          rm -rf private_key.pem

      - name: Remove Github Actions IP from GCP Firewall
        run: |
          gcloud compute firewall-rules delete allow-ssh-from-github
        if: always()