name: Deploy athlabs-frontend dev branch on Azure VM
on: 
  push: 
    branches: 
      - dev
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Get Github action IP 
        id: ip 
        uses: haythem/public-ip@v1.3 

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Add Github Actions IP to Azure Network Security Group
        run: |
          az network nsg rule create --resource-group Athlabs --name AllowSSHFromGitHub --nsg-name ${{ secrets.AZURE_NSG_NAME }} --priority 100 --access Allow --direction Inbound --protocol Tcp --source-address-prefixes ${{ steps.ip.outputs.ipv4 }}/24 --source-port-ranges '*' --destination-address-prefixes '*' --destination-port-ranges 22
          sleep 10
      - name: Deploy on Azure VM
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PK }}
          HOSTNAME: ${{ secrets.HOSTNAME_DEV }}
          USER_NAME: ${{ secrets.USERNAME_DEV }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            cd /home/azureuser/athlabs-main/athlabs-frontend
            git checkout dev
            git pull origin dev
            cd /home/azureuser/athlabs-main
            docker compose build frontend
            docker compose stop frontend
            yes | docker compose rm frontend
            docker compose up -d frontend
            yes | docker system prune -a --volumes
          '
          rm -rf private_key.pem

      - name: Remove Github Actions IP from Azure Network Security Group
        run: |
          az network nsg rule delete --resource-group Athlabs --name AllowSSHFromGitHub --nsg-name ${{ secrets.AZURE_NSG_NAME }}
        if: always()